<?php
/**
 * Plugin Name: WP Messenger Forward & Customer Chat
 * Description: Single-file plugin that forwards WordPress events to Bale, Telegram, and Rocket.Chat, and provides an attractive customer support chat that forwards messages to these platforms and relays replies back to customers.
 * Version: 2.0
 * Author: Generated by AI
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden.
}

/**
 * Main class for the plugin.
 */
class WP_Messenger_Forward {

	/**
	 * Plugin options name.
	 */
	const OPTION_NAME = 'wp_messenger_forward_settings';

	/**
	 * Default settings including messenger tokens and event toggles.
	 */
	public static function on_activate() {
		$default = array(
			'telegram_bot_token'       => '',
			'telegram_chat_id'         => '',
			'bale_bot_token'           => '',
			'bale_chat_id'             => '',
			'rocketchat_url'           => 'https://chat.example.com/api',
			'rocketchat_user'          => '',
			'rocketchat_token'         => '',
			'events'                   => array(
				'forward_comment'       => true,
				'forward_post_publish'  => true,
				'forward_user_create'   => true,
				'forward_order_created' => false,
				'forward_order_status'  => false,
				'forward_product_view'  => false,
				'forward_page_view'     => false,
			),
		);
		update_option( self::OPTION_NAME, $default );
	}

	/**
	 * Register admin menu and hooks.
	 */
	public static function init() {
		register_activation_hook( __FILE__, array( __CLASS__, 'on_activate' ) );
		add_action( 'admin_menu', array( __CLASS__, 'add_admin_menu' ) );
		add_action( 'init', array( __CLASS, 'add_shortcode' ) );

		// Conditional hooks based on enabled events.
		$opts = get_option( self::OPTION_NAME );
		$ev   = $opts['events'] ?? $default['events'];

		// Core WP events (always enabled for backwards compatibility).
		add_action( 'comment_post', array( __CLASS, 'forward_comment' ), 10, 1 );
		add_action( 'publish_post', array( __CLASS, 'forward_post_publish' ), 10, 1 );
		add_action( 'wp_insert_user', array( __CLASS, 'forward_user_create' ), 10, 1 );
		add_action( 'transition_post_status', array( __CLASS, 'forward_post_status_change' ), 10, 3 );

		// WooCommerce events (only if WooCommerce is active and enabled).
		if ( function_exists( 'wc' ) && $ev['forward_order_created'] ) {
			add_action( 'woocommerce_order_created', array( __CLASS, 'forward_order_created' ), 20, 1 );
		}
		if ( function_exists( 'wc' ) && $ev['forward_order_status'] ) {
			add_action( 'woocommerce_order_status_changed', array( __CLASS, 'forward_order_status_changed' ), 20, 3 );
		}
		if ( function_exists( 'wc' ) && $ev['forward_product_view'] ) {
			add_action( 'woocommerce_product_viewed', array( __CLASS, 'forward_product_viewed' ), 20, 1 );
		}
		// Page view forwarding (simple implementation – can be extended).
		if ( $ev['forward_page_view'] ) {
			add_action( 'template_redirect', array( __CLASS, 'forward_page_view' ) );
		}

		// Front-end support chat.
		add_shortcode( 'customer_chat', array( __CLASS, 'customer_chat_shortcode' ) );
		add_action( 'wp_ajax_forward_message', array( __CLASS, 'ajax_forward_message' ) );
		add_action( 'wp_ajax_send_reply', array( __CLASS, 'ajax_send_reply' ) );
	}

	/**
	 * Ensure defaults on every load.
	 */
	public static function ensure_defaults() {
		$opts = get_option( self::OPTION_NAME );
		$default = array(
			'telegram_bot_token'       => '',
			'telegram_chat_id'         => '',
			'bale_bot_token'           => '',
			'bale_chat_id'             => '',
			'rocketchat_url'           => 'https://chat.example.com/api',
			'rocketchat_user'          => '',
			'rocketchat_token'         => '',
			'events'                   => array(
				'forward_comment'       => true,
				'forward_post_publish'  => true,
				'forward_user_create'   => true,
				'forward_order_created' => false,
				'forward_order_status'  => false,
				'forward_product_view'  => false,
				'forward_page_view'     => false,
			),
		);
		foreach ( $default as $k => $v ) {
			if ( ! array_key_exists( $k, $opts ) ) {
				$opts[ $k ] = $v;
			}
		}
		// Merge events array safely.
		if ( ! isset( $opts['events'] ) || ! is_array( $opts['events'] ) ) {
			$opts['events'] = $default['events'];
		} else {
			$opts['events'] = array_merge( $default['events'], $opts['events'] );
		}
		update_option( self::OPTION_NAME, $opts );
	}

	/**
	 * Add admin menu under Settings.
	 */
	public static function add_admin_menu() {
		add_options_page(
			'Messenger Forward Settings',
			'Messenger Forward',
			'manage_options',
			'wp-messenger-forward',
			array( __CLASS, 'settings_page' )
		);
	}

	/**
	 * Settings page HTML.
	 */
	public static function settings_page() {
		self::ensure_defaults();
		$opts = get_option( self::OPTION_NAME );
		$updated = false;
		if ( isset( $_POST['wp_messenger_forward_save'] ) ) {
			// Sanitize messenger fields.
			$new = array(
				'telegram_bot_token'       => isset( $_POST['telegram_bot_token'] ) ? sanitize_text_field( $_POST['telegram_bot_token'] ) : '',
				'telegram_chat_id'         => isset( $_POST['telegram_chat_id'] ) ? sanitize_text_field( $_POST['telegram_chat_id'] ) : '',
				'bale_bot_token'           => isset( $_POST['bale_bot_token'] ) ? sanitize_text_field( $_POST['bale_bot_token'] ) : '',
				'bale_chat_id'             => isset( $_POST['bale_chat_id'] ) ? sanitize_text_field( $_POST['bale_chat_id'] ) : '',
				'rocketchat_url'           => isset( $_POST['rocketchat_url'] ) ? esc_url_raw( $_POST['rocketchat_url'] ) : '',
				'rocketchat_user'          => isset( $_POST['rocketchat_user'] ) ? sanitize_text_field( $_POST['rocketchat_user'] ) : '',
				'rocketchat_token'         => isset( $_POST['rocketchat_token'] ) ? sanitize_text_field( $_POST['rocketchat_token'] ) : '',
				// Merge events array.
				'events'                   => isset( $_POST['events'] ) && is_array( $_POST['events'] ) ? array_combine( array_keys( $opts['events'] ), array_map( 'boolval', $_POST['events'] ) ) : $opts['events'],
			);
			update_option( self::OPTION_NAME, $new );
			$updated = true;
		}
		?>
		<div class="wrap">
			<h1>Messenger Forward Settings</h1>
			<form method="post" action="">
				<table class="form-table">
					<!-- Messenger credentials -->
					<tr>
						<th><label for="telegram_bot_token">Telegram Bot Token</label></th>
						<td><input type="text" name="telegram_bot_token" id="telegram_bot_token" value="<?php echo esc_attr( $opts['telegram_bot_token'] ); ?>" class="large-text" placeholder="e.g. 123456789:ABCdefGHIjkLmnoPQRstU"></td>
					</tr>
					<tr>
						<th><label for="telegram_chat_id">Telegram Chat ID (target group/user)</label></th>
						<td><input type="text" name="telegram_chat_id" id="telegram_chat_id" value="<?php echo esc_attr( $opts['telegram_chat_id'] ); ?>" class="large-text" placeholder="e.g. -1001234567890"></td>
					</tr>
					<tr>
						<th><label for="bale_bot_token">Bale Bot Token</label></th>
						<td><input type="text" name="bale_bot_token" id="bale_bot_token" value="<?php echo esc_attr( $opts['bale_bot_token'] ); ?>" class="large-text" placeholder="e.g. 1234567890-abcdefghijklmnopqrstuvwxyz"></td>
					</tr>
					<tr>
						<th><label for="bale_chat_id">Bale Chat ID (target group/user)</label></th>
						<td><input type="text" name="bale_chat_id" id="bale_chat_id" value="<?php echo esc_attr( $opts['bale_chat_id'] ); ?>" class="large-text" placeholder="e.g. 1234567890"></td>
					</tr>
					<tr>
						<th><label for="rocketchat_url">Rocket.Chat API URL</label></th>
						<td><input type="text" name="rocketchat_url" id="rocketchat_url" value="<?php echo esc_attr( $opts['rocketchat_url'] ); ?>" class="large-text" placeholder="e.g. https://your.chat.com/api/v1"></td>
					</tr>
					<tr>
						<th><label for="rocketchat_user">Rocket.Chat User ID or Bot ID</label></th>
						<td><input type="text" name="rocketchat_user" id="rocketchat_user" value="<?php echo esc_attr( $opts['rocketchat_user'] ); ?>" class="large-text" placeholder="e.g. botId123"></td>
					</tr>
					<tr>
						<th><label for="rocketchat_token">Rocket.Chat Auth Token</label></th>
						<td><input type="text" name="rocketchat_token" id="rocketchat_token" value="<?php echo esc_attr( $opts['rocketchat_token'] ); ?>" class="large-text" placeholder="e.g. user_auth_token"></td>
					</tr>

					<!-- Events to forward -->
					<tr>
						<th colspan="2"><h3>Events to Forward</h3></th>
					</tr>
					<?php
					$event_labels = [
						'forward_comment'       => 'New comments',
						'forward_post_publish'  => 'Posts published',
						'forward_user_create'   => 'New user registrations',
						'forward_order_created' => 'WooCommerce orders created',
						'forward_order_status'  => 'WooCommerce order status changes',
						'forward_product_view'  => 'Product views',
						'forward_page_view'     => 'Page views',
					];
					foreach ( $event_labels as $key => $label ) {
						$checked = isset( $opts['events'][ $key ] ) && $opts['events'][ $key ] ? 'checked' : '';
						echo '<tr>';
						echo '<td style="vertical-align:middle;">';
						echo '<label>';
						echo '<input type="checkbox" name="events[' . $key . ']" value="1" ' . $checked . '>';
						echo ' ' . $label;
						echo '</label>';
						echo '</td>';
						echo '<td style="vertical-align:middle; font-size:0.9em;">';
						echo esc_html( $label );
						echo '</td>';
						echo '</tr>';
					}
					?>
				</table>
				<p class="submit">
					<input type="submit" name="wp_messenger_forward_save" id="wp_messenger_forward_save" class="button button-primary" value="Save Changes">
				</p>
			</form>
			<?php if ( $updated ) : ?>
				<div class="notice notice-success is-dismissible"><p><strong>Settings saved.</strong></p></div>
			<?php endif; ?>
		</div>
		<?php
	}

	/**
	 * Place a notice in wp_head (optional).
	 */
	public static function forward_event_notice() {
		// Could echo a comment for debugging.
		// echo '<!-- WP Messenger Forward active -->';
	}

	/**
	 * Forward comment posted to all configured messengers.
	 */
	public static function forward_comment( $comment_id ) {
		if ( ! ( get_option( self::OPTION_NAME )['events']['forward_comment'] ?? true ) ) return;
		$comment = get_comment( $comment_id );
		if ( ! $comment ) return;
		$opts = get_option( self::OPTION_NAME );
		$msg  = sprintf(
			"🗒️ New comment on %s\n%s: %s\nBy: %s (IP: %s)",
			get_the_title( $comment->comment_post_ID ),
			__( 'Commenter', 'wp-messenger-forward' ),
			esc_html( $comment->comment_author ),
			esc_html( $comment->comment_author_email ),
			esc_html( get_comment_type( $comment ) )
		);
		self::send_to_messengers( $msg );
	}

	/**
	 * Forward post publish event.
	 */
	public static function forward_post_publish( $post_id ) {
		$post = get_post( $post_id );
		if ( ! $post ) return;
		$opts = get_option( self::OPTION_NAME );
		if ( ! ( $opts['events']['forward_post_publish'] ?? true ) ) return;
		$msg  = sprintf(
			"📢 New post published:\n%s\n%s\n%s",
			esc_html( $post->post_title ),
			get_permalink( $post_id ),
			__( 'Check it out!', 'wp-messenger-forward' )
		);
		self::send_to_messengers( $msg );
	}

	/**
	 * Forward new user creation.
	 */
	public static function forward_user_create( $user_id ) {
		$user = get_user_by( 'id', $user_id );
		if ( ! $user ) return;
		$opts = get_option( self::OPTION_NAME );
		if ( ! ( $opts['events']['forward_user_create'] ?? true ) ) return;
		$msg  = sprintf(
			"👤 New user registered:\nUsername: %s\nEmail: %s\nRole: %s",
			esc_html( $user->user_login ),
			esc_html( $user->user_email ),
			implode( ', ', $user->roles )
		);
		self::send_to_messengers( $msg );
	}

	/**
	 * Forward WooCommerce order creation.
	 */
	public static function forward_order_created( $order_id ) {
		if ( ! function_exists( 'wc' ) ) return;
		$order = wc_get_order( $order_id );
		if ( ! $order ) return;
		$opts = get_option( self::OPTION_NAME );
		if ( ! ( $opts['events']['forward_order_created'] ?? false ) ) return;
		$msg  = sprintf(
			"🛒 New WooCommerce order #%d\nCustomer: %s (%s)\nTotal: %s\nStatus: %s\nLink: %s",
			$order->get_id(),
			esc_html( $order->get_billing_email() ),
			esc_html( $order->get_billing_first_name() . ' ' . $order->get_billing_last_name() ),
			$order->get_total(),
			$order->get_status(),
			get_permalink( $order_id )
		);
		self::send_to_messengers( $msg );
	}

	/**
	 * Forward WooCommerce order status change.
	 */
	public static function forward_order_status_changed( $order_id, $old_status, $new_status ) {
		if ( ! function_exists( 'wc' ) ) return;
		$order = wc_get_order( $order_id );
		if ( ! $order ) return;
		$opts = get_option( self::OPTION_NAME );
		if ( ! ( $opts['events']['forward_order_status'] ?? false ) ) return;
		$msg  = sprintf(
			"🔄 Order #%d status changed:\nFrom: %s\nTo: %s\nCustomer: %s\nLink: %s",
			$order->get_id(),
			$old_status,
			$new_status,
			esc_html( $order->get_billing_email() ),
			get_permalink( $order_id )
		);
		self::send_to_messengers( $msg );
	}

	/**
	 * Forward product view event.
	 */
	public static function forward_product_viewed( $product_id ) {
		if ( ! function_exists( 'wc' ) ) return;
		$product = wc_get_product( $product_id );
		if ( ! $product ) return;
		$opts = get_option( self::OPTION_NAME );
		if ( ! ( $opts['events']['forward_product_view'] ?? false ) ) return;
		$msg  = sprintf(
			"👁️ Product viewed: %s (ID: %d)\nLink: %s",
			esc_html( $product->get_name() ),
			$product_id,
			get_permalink( $product_id )
		);
		self::send_to_messengers( $msg );
	}

	/**
	 * Simple page view forward (fires on template_redirect).
	 */
	public static function forward_page_view() {
		// Optional: you can add logic to detect post/page ID and forward.
		// For now, just a placeholder message.
		$opts = get_option( self::OPTION_NAME );
		if ( ! ( $opts['events']['forward_page_view'] ?? false ) ) return;
		// Example: forward current page title if it's a singular post/page.
		if ( is_singular() ) {
			$post = get_post();
			$msg  = sprintf(
				"📄 Page view: %s\nURL: %s",
				esc_html( $post->post_title ),
				get_permalink( $post->ID )
			);
			self::send_to_messengers( $msg );
		}
	}

	/**
	 * Send the given message to all configured messengers.
	 */
	public static function send_to_messengers( $message ) {
		$opts = get_option( self::OPTION_NAME );

		// Telegram
		if ( ! empty( $opts['telegram_bot_token'] ) && ! empty( $opts['telegram_chat_id'] ) ) {
			self::telegram_send( $opts['telegram_bot_token'], $opts['telegram_chat_id'], $message );
		}

		// Bale
		if ( ! empty( $opts['bale_bot_token'] ) && ! empty( $opts['bale_chat_id'] ) ) {
			self::bale_send( $opts['bale_bot_token'], $opts['bale_chat_id'], $message );
		}

		// Rocket.Chat
		if ( ! empty( $opts['rocketchat_url'] ) && ! empty( $opts['rocketchat_token'] ) ) {
			self::rocketchat_send( $opts['rocketchat_url'], $opts['rocketchat_token'], $message );
		}
	}

	/**
	 * Send message via Telegram Bot API.
	 */
	private static function telegram_send( $bot_token, $chat_id, $text ) {
		$url = "https://api.telegram.org/bot{$bot_token}/sendMessage";
		$args = array(
			'headers' => array( 'Content-Type: application/json' ),
			'server'  => parse_url( $url, PHP_URL_HOST ),
			'body'    => json_encode( array( 'chat_id' => $chat_id, 'text' => $text ) ),
			'timeout' => 30,
		);
		$response = wp_remote_post( $url, $args );
		if ( is_wp_error( $response ) ) {
			error_log( 'Telegram error: ' . $response->get_error_message() );
		}
	}

	/**
	 * Send message via Bale Bot API.
	 */
	private static function bale_send( $bot_token, $chat_id, $text ) {
		$url = "https://api.bale.ai/bot{$bot_token}/sendMessage";
		$args = array(
			'headers' => array( 'Content-Type: application/json' ),
			'body'    => json_encode( array( 'chat_id' => $chat_id, 'text' => $text ) ),
			'timeout' => 30,
		);
		$response = wp_remote_post( $url, $args );
		if ( is_wp_error( $response ) ) {
			error_log( 'Bale error: ' . $response->get_error_message() );
		}
	}

	/**
	 * Send message to Rocket.Chat via its chat.post message API.
	 */
	private static function rocketchat_send( $url, $token, $text ) {
		$post_url = rtrim( $url, '/' ) . '/chat.postMessage';
		$args = array(
			'headers' => array(
				'Content-Type: application/json',
				'Authorization: Bearer ' . $token,
			),
			'body'    => json_encode( array( 'roomId' => 'YOUR_ROOM_ID', 'text' => $text ) ),
			'timeout' => 30,
		);
		$response = wp_remote_post( $post_url, $args );
		if ( is_wp_error( $response ) ) {
			error_log( 'Rocket.Chat error: ' . $response->get_error_message() );
		}
	}

	/**
	 * Shortcode: [customer_chat] – displays a minimal chat box.
	 */
	public static function customer_chat_shortcode() {
		ob_start();
		$opts = get_option( self::OPTION_NAME );
		?>
		<div id="wp-messenger-chat" style="
			position: fixed; right: 20px; bottom: 20px;
			width: 320px; max-height: 500px; background: #fff;
			border: 1px solid #ddd; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,.1);
			z-index: 9999; font-family: Arial, sans-serif;
		">
			<div style="background: #f7f7f7; padding: 10px; border-bottom: 1px solid #ddd; border-radius: 8px 8px 0 0;">
				<h3 style="margin:0; font-size:1.2rem;">Support Chat</h3>
				<span id="wp-chat-close" style="cursor:pointer; float:right; font-size:1.2rem;">×</span>
			</div>
			<div id="wp-chat-messages" style="height: 300px; overflow-y: auto; padding: 10px; font-size: 0.9rem;">
				<?php // Messages will be loaded via AJAX; here we just show a placeholder. ?>
				<p class="empty"><?php _e( 'Start a conversation...', 'wp-messenger-forward' ); ?></p>
			</div>
			<div id="wp-chat-input" style="padding: 10px; border-top: 1px solid #ddd; display: none;">
				<input type="text" id="wp-chat-message" style="width: 80%; padding: 6px; border: 1px solid #ccc; border-radius: 4px;">
				<button id="wp-chat-send" style="margin-left: 10px; padding: 0 12px; background: #2962ff; color: #fff; border: none; border-radius: 4px; cursor: pointer;">Send</button>
			</div>
		</div>

		<script type="text/javascript">
			jQuery(function($){
				var $chat = $('#wp-messenger-chat');
				var $messages = $('#wp-chat-messages');
				var $input = $('#wp-chat-message');
				var $send   = $('#wp-chat-send');
				var $close  = $('#wp-chat-close');

				// Toggle chat box
				$chat.on('click', function(){
					$chat.toggleClass('expanded');
					if ( $chat.hasClass('expanded') ) {
						$input.parent().show();
					} else {
						$input.parent().hide();
					}
				});
				$close.on('click', function(){
					$chat.removeClass('expanded');
					$input.parent().hide();
				});

				// Send message
				$.send_chat_message = function(text){
					$.ajax({
						url: wpajax_obj.ajax_url,
						type: 'POST',
						data: {
							action: 'forward_message',
							message: text,
							nonce: wpajax_obj.nonce
						},
						success: function(res){
							if ( res.success ) {
								$messages.append('<p><strong>You:</strong> ' + text + '</p>');
								$messages.scrollTop( $messages[0].scrollHeight );
								$input.val('').focus();
							}
						},
						error: function(){
							alert('Error sending message.');
						}
					});
				};

				$send.on('click', function(){
					var txt = $input.val().trim();
					if ( txt ) {
						$.send_chat_message( txt );
					}
				});
				$input.on('keypress', function(e){
					if ( e.which === 13 ) { // Enter
						$( '.wp-chat-send' ).trigger('click');
					}
				});

				// Load existing messages (optional)
				$.ajax({
					url: wpajax_obj.ajax_url,
					type: 'POST',
					data: {
						action: 'load_chat_messages',
						nonce: wpajax_obj.nonce
					},
					success: function(res){
						if ( res.messages ) {
							$.each(res.messages, function(i, m){
								$messages.append('<p><strong>' + m.sender + ':</strong> ' + m.text + '</p>');
							});
							$messages.scrollTop( $messages[0].scrollHeight );
						}
					}
				});
			});
		</script>
		<?php
		// Pass AJAX URL and nonce to JS.
		$nonce = wp_create_nonce( 'forward_message_nonce' );
		$script = '<script>window.wpajax_obj = { ajax_url: "' . admin_url( 'admin-ajax.php' ) . '", nonce: "' . $nonce . '" };</script>';
		echo $script;
		$content = ob_get_clean();
		return $content;
	}

	/**
	 * AJAX handler: forward a customer message to all messengers.
	 */
	public static function ajax_forward_message() {
		check_ajax_referer( 'forward_message_nonce', 'nonce' );
		if ( ! current_user_can( 'edit_posts' ) ) {
			wp_send_json_error( 'Unauthorized' );
		}
		$message = isset( $_POST['message'] ) ? sanitize_text_field( $_POST['message'] ) : '';
		if ( ! $message ) {
			wp_send_json_error( 'Empty message' );
		}
		self::send_to_messengers( $message );
		wp_send_json_success( array( 'status' => 'forwarded' ) );
	}

	/**
	 * AJAX handler: send a reply back to the customer via the messengers.
	 * Uses the same chat IDs that are configured in the settings, so the reply
	 * appears in the same conversation thread where the original message arrived.
	 */
	public static function ajax_send_reply() {
		check_ajax_referer( 'forward_message_nonce', 'nonce' );
		if ( ! current_user_can( 'edit_posts' ) ) {
			wp_send_json_error( 'Unauthorized' );
		}
		$reply   = isset( $_POST['reply'] ) ? sanitize_text_field( $_POST['reply'] ) : '';
		if ( ! $reply ) {
			wp_send_json_error( 'Empty reply' );
		}
		// Prefix the reply so it's clear it's a response.
		$formatted = sprintf(
			"💬 Reply:\n%s",
			$reply
		);
		self::send_to_messengers( $formatted );
		wp_send_json_success( array( 'status' => 'replied' ) );
	}
}

// Ensure defaults on every load.
WP_Messenger_Forward::ensure_defaults();

// Initialize the plugin hooks.
WP_Messenger_Forward::init();
