#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# fix_wsgi_mount.sh — wire the Scraper4 main site into the PythonAnywhere
# WSGI without touching pip/venv, so it works around a quota-failed install.
#
# The /deployer installer leaves a guarded placeholder WSGI when the main
# site is not configured ("Scraper4 main site is not configured yet..."),
# and install_pythonanywhere.sh never reaches the WSGI step if dependency
# install fails with Disk quota exceeded. This script ONLY rewrites the
# WSGI: main site at /, the deployer at /deployer/ (kept when mounted).
#
# Run from the PythonAnywhere Bash console, from ~:
#   bash fix_wsgi_mount.sh
#
# Optional env vars:
#   DEPLOYER_PA_USER      account name (default: whoami)
#   DEPLOYER_PA_API       PythonAnywhere API base (default real API)
#   DEPLOYER_VARWWW       WSGI search dir            (default /var/www)
#   DEPLOYER_HEALTH_URL   health URL to poll after reload
#   DEPLOYER_APP_DIR      scraper4 app dir           (default ~/scraper4)
#   DEPLOYER_WSGI_FILE    explicit WSGI file
#   DEPLOYER_OFFLINE      0/1: skip API reload (default 0)
# ---------------------------------------------------------------------------
set -Eeuo pipefail
umask 077

USER_NAME="${DEPLOYER_PA_USER:-$(id -un)}"
USER_LOWER="$(printf '%s' "$USER_NAME" | tr '[:upper:]' '[:lower:]')"
HOME_DIR="$HOME"
DOMAIN="${USER_LOWER}.pythonanywhere.com"
APP_DIR="${DEPLOYER_APP_DIR:-$HOME_DIR/scraper4}"
APP_FILE="$APP_DIR/scraper4.py"
DATA_FILE="$APP_DIR/scraper4_data.json"
PASSWORD_FILE="$APP_DIR/admin_password.txt"
VENV_DIR="$APP_DIR/venv"
TOKEN_FILE="$HOME_DIR/.pythonanywhere_api_token"
VARWWW="${DEPLOYER_VARWWW:-/var/www}"
API="${DEPLOYER_PA_API:-https://www.pythonanywhere.com/api/v0/user/$USER_NAME}"
HEALTH_URL="${DEPLOYER_HEALTH_URL:-https://$DOMAIN/health}"
SYSTEM_PY="$(command -v python3 || true)"
REPO="${DEPLOYER_REPO:-fazilatma/amphp}"
SOURCE_BRANCH="${DEPLOYER_SOURCE_BRANCH:-arena/01a06abd-amphp}"
GITHUB_API="${DEPLOYER_GITHUB_API:-https://api.github.com}"
JSDELIVR="${DEPLOYER_JSDELIVR:-https://cdn.jsdelivr.net}"

# --- robust GitHub download (API first; raw/jsDelivr fallbacks) ---------------
download_github_file() {
    local dest="$1" rel="$2"
    if curl -fsSL --retry 3 --connect-timeout 20 --max-time 90 \
         -H 'Accept: application/vnd.github.raw' \
         -o "$dest" "$GITHUB_API/repos/$REPO/contents/$rel?ref=$SOURCE_BRANCH" 2>/dev/null \
       && [ -s "$dest" ]; then
        echo "==> دانلود از GitHub API: $rel"
        return 0
    fi
    if curl -fsSL --retry 3 --connect-timeout 20 --max-time 90 \
         -o "$dest" "https://raw.githubusercontent.com/$REPO/$SOURCE_BRANCH/$rel" 2>/dev/null && [ -s "$dest" ]; then
        echo "==> دانلود از raw.githubusercontent: $rel"
        return 0
    fi
    if curl -fsSL --retry 3 --connect-timeout 20 --max-time 90 \
         -o "$dest" "$JSDELIVR/gh/$REPO@$SOURCE_BRANCH/$rel" 2>/dev/null && [ -s "$dest" ]; then
        echo "==> دانلود از jsDelivr CDN: $rel"
        return 0
    fi
    return 1
}

fail(){ echo "ERROR: $*" >&2; exit 1; }

[ -f "$APP_FILE" ] || fail "فایل سایت پیدا نشد: $APP_FILE — اول install_pythonanywhere.sh را اجرا کنید یا DEPLOYER_APP_DIR را بدهید"

# --- make sure the deployer app itself is present and current (stdlib-only) ---
DEPLOYER_DIR="$HOME_DIR/.deployer"
mkdir -p "$DEPLOYER_DIR"
if [ "${DEPLOYER_OFFLINE:-0}" != 1 ]; then
    if download_github_file "$DEPLOYER_DIR/deployer.py" "deployer.py"; then
        echo "==> deployer.py به‌روزرسانی شد → $DEPLOYER_DIR/deployer.py"
    elif [ ! -f "$DEPLOYER_DIR/deployer.py" ]; then
        echo "!! دانلود deployer.py ناموفق بود؛ صفحه /deployer خطای روشن نشان می‌دهد" >&2
    else
        echo "!! دانلود deployer.py ناموفق بود؛ نسخه موجود (~/.deployer) استفاده می‌شود"
    fi
fi
# Regenerate deployer_wsgi.py only when it is missing or fails to import.
if ! "$SYSTEM_PY" -c 'import sys; sys.path.insert(0, sys.argv[1]); import deployer_wsgi' "$DEPLOYER_DIR" >/dev/null 2>&1; then
    echo "==> deployer_wsgi.py ناقص است؛ بازسازی…"
    "$SYSTEM_PY" - "$DEPLOYER_DIR/deployer_wsgi.py" "$REPO" "${DEPLOYER_BRANCHES:-}" "$APP_FILE" <<'PY'
import json, os, sys
path, repo, branches, target = sys.argv[1:5]
env = {"DEPLOYER_REPO": repo, "DEPLOYER_TARGET": target}
if branches:
    env["DEPLOYER_BRANCHES"] = branches
lines = [
    "# Auto-generated by fix_wsgi_mount.sh — do not edit by hand.",
    "import os, sys",
    "_d = os.path.expanduser('~/.deployer')",
    "if _d not in sys.path:",
    "    sys.path.insert(0, _d)",
    "os.environ.update(" + json.dumps(env) + ")",
    "import deployer",
    "application = deployer.wsgi_application",
]
with open(path, "w", encoding="utf-8") as fh:
    fh.write("\n".join(lines) + "\n")
PY
fi

find_wsgi(){ local f; for f in "$VARWWW/${USER_LOWER}_pythonanywhere_com_wsgi.py" "$VARWWW/${USER_NAME}_pythonanywhere_com_wsgi.py"; do [ -f "$f" ] && { printf '%s' "$f"; return; }; done; find "$VARWWW" -maxdepth 1 -type f -name '*_wsgi.py' -writable 2>/dev/null | sort | head -n1; }
WSGI_FILE="${DEPLOYER_WSGI_FILE:-$(find_wsgi || true)}"
[ -n "$WSGI_FILE" ] || fail "هیچ فایل WSGI قابل نوشتن در $VARWWW پیدا نشد"
[ -w "$WSGI_FILE" ] || fail "فایل WSGI قابل نوشتن نیست: $WSGI_FILE"
echo "==> WSGI: $WSGI_FILE"

# --- site-packages: prefer the app venv --------------------------------------
SITE_PACKAGES=""
if [ -x "$VENV_DIR/bin/python" ]; then
    SITE_PACKAGES="$("$VENV_DIR/bin/python" -c 'import sysconfig;print(sysconfig.get_paths()["purelib"])' 2>/dev/null || true)"
elif [ -n "$SYSTEM_PY" ]; then
    SITE_PACKAGES="$("$SYSTEM_PY" -c 'import sysconfig;print(sysconfig.get_paths()["purelib"])' 2>/dev/null || true)"
fi
echo "==> venv: $VENV_DIR"
echo "==> site-packages: ${SITE_PACKAGES:-(system/handled by PYTHONPATH)}"

# --- admin password (create only when it does not exist) ----------------------
if [ -s "$PASSWORD_FILE" ]; then
    ADMIN_PASSWORD="$(tr -d '\r\n' < "$PASSWORD_FILE")"
else
    ADMIN_PASSWORD="$("$SYSTEM_PY" -c 'import secrets;print(secrets.token_urlsafe(32))' 2>/dev/null || echo "deployer-wsgi-no-password")"
    printf '%s\n' "$ADMIN_PASSWORD" > "$PASSWORD_FILE"
    chmod 600 "$PASSWORD_FILE"
    echo "==> رمز ادمین ساخته شد: $PASSWORD_FILE"
fi

# --- import check (informational; never blocks the WSGI write) ----------------
IMPORT_OK=0
IMPORT_MSG=""
if [ -x "$VENV_DIR/bin/python" ]; then
    set +e
    IMPORT_MSG="$(cd "$APP_DIR" && "$VENV_DIR/bin/python" -c 'import scraper4;print(scraper4.APP_VERSION)' 2>&1)"
    RC=$?
    set -e
    if [ "$RC" = 0 ]; then IMPORT_OK=1; fi
fi
if [ "$IMPORT_OK" = 1 ]; then
    echo "==> آزمون import: OK (v$IMPORT_MSG)"
else
    echo "==> آزمون import: مشکل دارد ($IMPORT_MSG)" | head -c 300 || true
    echo
    echo "    WSGI همچنان نوشته می‌شود؛ اگر سایت بعد از reload خطای 'Missing dependency' داد،"
    echo "    وابستگی‌ها را نصب کنید:  cd ~ && bash install_pythonanywhere.sh"
fi
[ -n "$IMPORT_MSG" ] || IMPORT_MSG=""

# --- write the composite WSGI ---------------------------------------------------
TS="$(date +%Y%m%d-%H%M%S)"
cp -f "$WSGI_FILE" "$WSGI_FILE.bak.$TS"
echo "==> پشتیبان: $WSGI_FILE.bak.$TS"

export APP_DIR_E APP_FILE_E DATA_FILE_E SITE_E PASSWORD_E VENV_DIR_E WSGI_FILE_E BROWSER_PATH_E
APP_DIR_E="$APP_DIR"; APP_FILE_E="$APP_FILE"; DATA_FILE_E="$DATA_FILE"
SITE_E="$SITE_PACKAGES"; PASSWORD_E="$ADMIN_PASSWORD"; VENV_DIR_E="$VENV_DIR"
WSGI_FILE_E="$WSGI_FILE"
BROWSER_PATH_E="$APP_DIR/ms-playwright"
if [ -d /tmp/scraper4-${USER_NAME}-playwright ]; then BROWSER_PATH_E="/tmp/scraper4-${USER_NAME}-playwright"; fi

"$SYSTEM_PY" - <<'PY'
import os
lines = [
    "# Auto-generated by fix_wsgi_mount.sh — do not edit by hand.",
    "# --- scraper4 deployer mount (managed by fix_wsgi_mount.sh) ---",
    "# --- guarded WSGI v2: a broken import never takes down the whole site ---",
    "import os, site, sys, traceback",
]
site_p = os.environ["SITE_E"]
if site_p:
    lines.append("site.addsitedir(" + repr(site_p) + ")")
app_dir = os.environ["APP_DIR_E"]
err_file = app_dir + "/wsgi_error.txt"
lines += [
    "APP_DIRECTORY=" + repr(app_dir),
    "if APP_DIRECTORY not in sys.path: sys.path.insert(0, APP_DIRECTORY)",
    "os.environ['SCRAPER_PASSWORD']=''",
    "os.environ['SCRAPER_DEPLOY_PASSWORD']=" + repr(os.environ["PASSWORD_E"]),
    "os.environ['SCRAPER_DATA_FILE']=" + repr(os.environ["DATA_FILE_E"]),
    "os.environ['PLAYWRIGHT_BROWSERS_PATH']=" + repr(os.environ["BROWSER_PATH_E"]),
    "os.environ['SCRAPER_PLAYWRIGHT_PATH']=" + repr(os.environ["BROWSER_PATH_E"]),
    "",
    "__wsgi_err = " + repr(err_file),
    "__main_app = None",
    "__main_error = ''",
    "try:",
    "    from scraper4 import app as __main_app",
    "except Exception:",
    "    __main_error = traceback.format_exc()",
    "    try:",
    "        with open(__wsgi_err, 'w', encoding='utf-8') as _f: _f.write(__main_error)",
    "    except Exception: pass",
    "",
    "__deployer_app = None",
    "__deployer_error = ''",
    "try:",
    "    _d = os.path.expanduser('~/.deployer')",
    "    if _d not in sys.path: sys.path.insert(0, _d)",
    "    from deployer_wsgi import application as __deployer_app",
    "except Exception:",
    "    __deployer_error = traceback.format_exc()",
    "    try:",
    "        with open(os.path.join(_d, 'wsgi_error.txt'), 'w', encoding='utf-8') as _f: _f.write(__deployer_error)",
    "    except Exception: pass",
    "",
    "def _short(exc):",
    "    ll = [l for l in str(exc).strip().splitlines() if l.strip()]",
    "    return ll[-1] if ll else 'unknown'",
    "",
    "def application(environ, start_response):",
    "    path = environ.get('PATH_INFO', '')",
    "    if path.startswith('/deployer'):",
    "        if __deployer_app is not None:",
    "            return __deployer_app(environ, start_response)",
    "        body = ('دیپلوی‌ر در دسترس نیست: ' + _short(__deployer_error) + '\\nجزئیات: ~/.deployer/wsgi_error.txt — install_deployer_webapp.sh را دوباره اجرا کنید').encode('utf-8')",
    "        start_response('503 Service Unavailable', [('Content-Type', 'text/plain; charset=utf-8'), ('Content-Length', str(len(body)))])",
    "        return [body]",
    "    if __main_app is not None:",
    "        return __main_app(environ, start_response)",
    "    body = ('سایت اصلی در دسترس نیست: ' + _short(__main_error) + '\\nجزئیات: ' + __wsgi_err + ' — اول وابستگی‌ها را نصب کنید: bash install_pythonanywhere.sh').encode('utf-8')",
    "    start_response('503 Service Unavailable', [('Content-Type', 'text/plain; charset=utf-8'), ('Content-Length', str(len(body)))])",
    "    return [body]",
    "",
]
path = os.environ["WSGI_FILE_E"]
content = "\n".join(lines)
# /var/www lives on a different filesystem from /home on PythonAnywhere, so a
# rename from app_dir (home) to /var/www fails with EXDEV. Write the temp file
# next to the WSGI itself and only drop back to a direct write if needed.
try:
    tmp = os.path.join(os.path.dirname(path), ".wsgi.tmp")
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(content)
    try:
        os.replace(tmp, path)
    except OSError:
        import shutil
        shutil.copyfile(tmp, path)
        try:
            os.unlink(tmp)
        except OSError:
            pass
except OSError:
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
PY
echo "==> WSGI نوشته شد (محافظت‌شده: سایت اصلی + /deployer)"

# --- sanity parse of the new WSGI ------------------------------------------------
"$SYSTEM_PY" -c 'import ast,sys;ast.parse(open(sys.argv[1],encoding="utf-8").read());print("==> WSGI syntax OK")' "$WSGI_FILE"

# --- reload --------------------------------------------------------------------------
RELOAD_OK=0
if [ "${DEPLOYER_OFFLINE:-0}" != 1 ] && [ -s "$TOKEN_FILE" ]; then
    TOKEN="$(tr -d '[:space:]' < "$TOKEN_FILE")"
    echo "==> reload از API..."
    CODE="$(curl -sS -o /dev/null -w '%{http_code}' -X POST \
        -H "Authorization: Token $TOKEN" --connect-timeout 20 --max-time 120 \
        "$API/webapps/$DOMAIN/reload/" || true)"
    if [ "$CODE" = 200 ] || [ "$CODE" = 201 ]; then RELOAD_OK=1; echo "==> reload شد ✔"; else
        echo "==> reload API: HTTP $CODE — لمس WSGI به عنوان جایگزین"
        touch "$WSGI_FILE"
    fi
else
    echo "==> توکن API پیدا نشد — لطفاً در تب Web دکمه Reload را بزنید"
fi

# --- health check ---------------------------------------------------------------------
# The main site may still need dependencies, but the deployer is independent:
# consider the fix successful when EITHER endpoint is 200.
LIVE=000
DEPLOYER_STATUS_URL="https://$DOMAIN/deployer/status"
for n in $(seq 1 12); do
    sleep 5
    LIVE="$(curl -sS -o /dev/null -w '%{http_code}' --connect-timeout 15 --max-time 30 "$HEALTH_URL" || true)"
    if [ "$LIVE" = 200 ]; then break; fi
    DEPL_CODE="$(curl -sS -o /dev/null -w '%{http_code}' --connect-timeout 15 --max-time 30 "$DEPLOYER_STATUS_URL" || true)"
    if [ "$DEPL_CODE" = 200 ]; then
        LIVE=200
        echo "Health $n/12: سایت اصلی HTTP $(curl -sS -o /dev/null -w '%{http_code}' --connect-timeout 15 --max-time 30 "$HEALTH_URL" || true) (مشکل دارد) — ولی /deployer HTTP 200 ✔"
        break
    fi
    echo "Health $n/12: اصلی HTTP $LIVE / دیپلوی‌ر HTTP $DEPL_CODE"
done
if [ "$LIVE" != 200 ]; then
    echo "⚠️  سلامت سایت: HTTP $LIVE — بررسی لاگ‌های پایتون‌انی‌ورلد:"
    for log in "/var/log/${DOMAIN}.error.log" "/var/log/${DOMAIN}.server.log"; do
        [ -r "$log" ] && { echo "===== $log ====="; tail -n 60 "$log"; }
    done
fi

echo
echo "============================================================"
echo "✅ WSGI وصل شد: $WSGI_FILE"
echo "   سایت اصلی:  https://$DOMAIN/"
echo "   دیپلوی‌ر:   https://$DOMAIN/deployer/"
echo "   سلامت:      HTTP $LIVE"
[ "$IMPORT_OK" = 1 ] || echo "   ⚠️  import هنوز OK نیست — $IMPORT_MSG"
echo "============================================================"
[ "$LIVE" = 200 ] || echo "نکته: اگر import مشکل دارد، اول وابستگی‌ها را کامل کنید (install_pythonanywhere.sh) و دوباره این اسکریپت را اجرا کنید."
